const CATALOG = [
    {
        id: 'el1',
        name: 'Чизбургер',
        img: '../images/burgers/1.jpg',
        price: 50,
    },
    {
        id: 'el2',
        name: 'Гамбургер',
        img: '../images/burgers/2.jpg',
        price: 50,
    },
    {
        id: 'el3',
        name: 'Чикенбургер',
        img: '../images/burgers/3.jpg',
        price: 50,
    },
    {
        id: 'el4',
        name: 'Двойной Чизбургер',
        img: '../images/burgers/4.jpg',
        price: 100,
    },
    {
        id: 'el5',
        name: 'Чизбургер с беконом',
        img: '../images/burgers/5.jpg',
        price: 160,
    },
    {
        id: 'el6',
        name: 'Чизбургер Де Люкс',
        img: '../images/burgers/6.jpg',
        price: 165,
    },
    {
        id: 'el7',
        name: 'AramBurger',
        img: '../images/burgers/7.jpg',
        price: 200,
    },
    {
        id: 'el8',
        name: 'Кинг бургер',
        img: '../images/burgers/8.jpg',
        price: 210,
    },
        {
        id: 'elem1',
        name: 'Пепперони',
        img: '../images/pizza/1.jpg',
        price: 475,
    },
    {
        id: 'elem2',
        name: 'Сырная 🌱',
        img: '../images/pizza/2.jpg',
        price: 425,
    },
    {
        id: 'elem3',
        name: 'Ветчина и сыр',
        img: '../images/pizza/3.jpg',
        price: 475,
    },
    {
        id: 'elem4',
        name: 'Чизбургер-пицца',
        img: '../images/pizza/4.jpeg',
        price: 550,
    },
    {
        id: 'elem5',
        name: 'Четыре сыра 🌱',
        img: '../images/pizza/5.jpg',
        price: 550,
    },
    {
        id: 'elem6',
        name: 'Двойная пепперони',
        img: '../images/pizza/6.jpg',
        price: 550,
    },
    {
        id: 'elem7',
        name: 'Маргарита 🌱',
        img: '../images/pizza/7.jpeg',
        price: 400,
    },
    {
        id: 'elem8',
        name: 'Мексиканская 🌶️🌶️',
        img: '../images/pizza/8.jpg',
        price: 666,
    },
    {
        id: 'elem11',
        name: 'Калифорния',
        img: '../images/sushi/1.jpg',
        price: 465,
    },
    {
        id: 'elem22',
        name: 'Филадельфия',
        img: '../images/sushi/2.jpg',
        price: 475,
    },
    {
        id: 'elem33',
        name: 'Теплый лосось',
        img: '../images/sushi/3.jpg',
        price: 425,
    },
    {
        id: 'elem44',
        name: 'Сэнсэй 🌶️',
        img: '../images/sushi/4.jpg',
        price: 425,
    },
    {
        id: 'elem55',
        name: 'Аригато',
        img: '../images/sushi/5.jpg',
        price: 400,
    },
    {
        id: 'elem66',
        name: 'Ямато 🌶️',
        img: '../images/sushi/6.jpg',
        price: 425,
    },
    {
        id: 'elem77',
        name: 'Даку',
        img: '../images/sushi/7.jpg',
        price: 455,
    },
    {
        id: 'elem88',
        name: 'Дракон',
        img: '../images/sushi/8.jpg',
        price: 460,
    },
    {
        id: 'element1',
        name: 'Пепси 250мл',
        img: '../images/drink/1.jpg',
        price: 50,
    },
    {
        id: 'element2',
        name: 'Пепси 1000мл',
        img: '../images/drink/2.jpg',
        price: 100,
    },
    {
        id: 'element3',
        name: 'Липтон лимон 1000мл',
        img: '../images/drink/3.jpg',
        price: 100,
    },
    {
        id: 'element4',
        name: 'Липтон Лайм Юзу 1000мл',
        img: '../images/drink/4.jpg',
        price: 100,
    },
    {
        id: 'element5',
        name: 'Липтон земляника и клюква 1000мл',
        img: '../images/drink/5.jpg',
        price: 100,
    },
    {
        id: 'element6',
        name: 'Миринда 250мл',
        img: '../images/drink/6.jpg',
        price: 50,
    },
    {
        id: 'element7',
        name: 'Миринда 1000мл',
        img: '../images/drink/7.jpg',
        price: 100,
    },
    {
        id: 'element8',
        name: 'Аква минерале (без газа) 1000мл',
        img: '../images/drink/8.jpg',
        price: 70,
    },
        {
        id: 'element9',
        name: 'Аква минерале (с газом) 1000мл',
        img: '../images/drink/9.jpg',
        price: 70,
    },
];